services:
  db:
    image: postgres:16-alpine
    container_name: freshcut-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-freshcut_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_here}
      POSTGRES_DB: ${POSTGRES_DB:-freshcut_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db-net

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_KKIAPAY_PUBLIC_KEY: ${NEXT_PUBLIC_KKIAPAY_PUBLIC_KEY}
        NEXT_PUBLIC_KKIAPAY_ENVIRONMENT: ${NEXT_PUBLIC_KKIAPAY_ENVIRONMENT}
    container_name: freshcut-web
    restart: always
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-freshcut_admin}:${POSTGRES_PASSWORD:-secure_password_here}@db:5432/${POSTGRES_DB:-freshcut_db}?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-some_long_random_string_here}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost}
      RESEND_API_KEY: ${RESEND_API_KEY}
      SEED_DB: ${SEED_DB:-false}
      NEXT_PUBLIC_KKIAPAY_PUBLIC_KEY: ${NEXT_PUBLIC_KKIAPAY_PUBLIC_KEY}
      NEXT_PUBLIC_KKIAPAY_ENVIRONMENT: ${NEXT_PUBLIC_KKIAPAY_ENVIRONMENT}
      KKIAPAY_PRIVATE_KEY: ${KKIAPAY_PRIVATE_KEY}
      KKIAPAY_SECRET_KEY: ${KKIAPAY_SECRET_KEY}
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      # Tells Traefik which network to use to connect to this container
      - "traefik.docker.network=traefik-public"
      # Route HTTPS traffic for the configured domain
      - "traefik.http.routers.freshcut.rule=Host(`${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.freshcut.entrypoints=websecure"
      - "traefik.http.routers.freshcut.tls.certresolver=letsencrypt"
      - "traefik.http.services.freshcut.loadbalancer.server.port=3000"
      # Redirect HTTP traffic to HTTPS
      - "traefik.http.routers.freshcut-http.rule=Host(`${DOMAIN_NAME:-localhost}`)"
      - "traefik.http.routers.freshcut-http.entrypoints=web"
      - "traefik.http.routers.freshcut-http.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - db-net
      - traefik-public

volumes:
  postgres_data:

networks:
  db-net:
  traefik-public:
    external: true
