services:
  db:
    image: postgres:16-alpine
    container_name: freshcut-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-freshcut_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password_here}
      POSTGRES_DB: ${POSTGRES_DB:-freshcut_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432" # Changed from 5432 to 5433 to avoid conflicts with host PostgreSQL

  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_KKIAPAY_PUBLIC_KEY: ${NEXT_PUBLIC_KKIAPAY_PUBLIC_KEY}
        NEXT_PUBLIC_KKIAPAY_ENVIRONMENT: ${NEXT_PUBLIC_KKIAPAY_ENVIRONMENT}
    container_name: freshcut-web
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-freshcut_admin}:${POSTGRES_PASSWORD:-secure_password_here}@db:5432/${POSTGRES_DB:-freshcut_db}?schema=public
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET:-some_long_random_string_here}
      NEXTAUTH_URL: ${NEXTAUTH_URL:-http://localhost:3000}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3000}
      RESEND_API_KEY: ${RESEND_API_KEY}
      SEED_DB: ${SEED_DB:-false}
      NEXT_PUBLIC_KKIAPAY_PUBLIC_KEY: ${NEXT_PUBLIC_KKIAPAY_PUBLIC_KEY}
      NEXT_PUBLIC_KKIAPAY_ENVIRONMENT: ${NEXT_PUBLIC_KKIAPAY_ENVIRONMENT}
      KKIAPAY_PRIVATE_KEY: ${KKIAPAY_PRIVATE_KEY}
      KKIAPAY_SECRET_KEY: ${KKIAPAY_SECRET_KEY}
    depends_on:
      - db

volumes:
  postgres_data:
